# -*- coding: utf-8 -*-
"""ADSTI_EX21.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KXG5_TwwHZRNAWq44vCImsWcO-ydQTL

# **Carregamento**
"""

#Ler o data set:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset.info ()

"""# **.plot ()**"""

#Gráfico Preço x Imóvel:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset["price"].plot ()

"""# **Configurando**"""

#Gráfico Preço x Número de Quartos:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset.plot (x = "bedrooms", y = "price", kind = "scatter", title = "Preço x Número de Quartos", color = "r")

#Dados usados no gráfico de dispersão Preço x Número de Quartos:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
tabela = dataset[["bedrooms", "price"]].sort_values (by = "price")
tabela.columns = ["Quartos", "Preço"]
tabela

#Gráfico Preço x Número de Banheiros:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset.plot (x = "bathrooms", y = "price", kind = "scatter", title = "Preço x Número de Banheiros", color = "y")

"""# **Histograma**"""

#Histograma do número de quartos dos imóveis:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset.hist (column = "bedrooms")

#Histograma do número de quartos dos imóveis:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset["bedrooms"].hist ()

#Histograma do número de quartos dos imóveis:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset["bedrooms"].hist (bins = 30, alpha = 0.5, color = "green")

#Histogramas do número de quartos e do número de banheiros dos imóveis:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset[["bedrooms", "bathrooms"]].hist (bins = 30, alpha = 0.65, color= "red")

#Histogramas do número de quartos, do número de banheiros e dos preçosdos imóveis:
import pandas as pd
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
dataset[["bedrooms", "bathrooms", "price"]].hist (bins = 30, alpha = 0.45, color = "blue")

"""# **Estilos**"""

#Boxplot do número de quarto dos imóveis:
import pandas as pd
import matplotlib as mpl
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
mpl.style.use ("ggplot")
dataset.boxplot (column = "bedrooms")

#Boxplot da distribuição de preços por número de quartos dos imóveis:
import pandas as pd
import matplotlib as mpl
uri = "https://raw.githubusercontent.com/moderndive/moderndive/master/data-raw/kc_house_data.csv"
dataset = pd.read_csv (uri)
mpl.style.use ("ggplot")
dataset.boxplot (column = "price", by = "bedrooms")

"""# **Exercício**"""

1. Ler o data set

#Ler o data set:
import pandas as pd
uri = "https://raw.githubusercontent.com/wcota/covid19br/master/cases-brazil-total.csv"
dataset = pd.read_csv (uri)
dataset.info ()

"""2. Apresentar os registros do "data set"."""

dataset.head()

"""3. Apresentar o gráfico do número total de casos."""

import matplotlib
dataset["totalCases"].plot ()

"""4. Apresentar o gráfico do número total de casos segundo o ministério da saúde."""

import matplotlib
dataset.plot (x = "totalCases", y = "state", kind = "scatter", title = "total de casos segundo o ministério da saúde", color = "y")

"""5. Apresentar o gráfico de dispersão do número de mortes pelo número de casos:"""

import matplotlib
dataset.plot (x = "totalCases", y = "deaths", kind="scatter",  title = "total de casos pelo número de mortes", color = "red")

"""6. Apresentar o gráfico de dispersão do número de mortes segundo o ministério da
saúde pelo número de casos também segundo o ministério da saúde:
"""

import matplotlib
dataset.plot (x = "totalCases", y = "deaths", kind="scatter",  title = "total de casos pelo número de mortes segundo o ministério da saúde", color = "red")

"""7. Apresentar o gráfico de linha do número total de casos por estado."""

import pandas as pd

dataset[["totalCases", "state"]].hist (bins = 30, alpha = 0.45, color = "blue")

"""8. Apresentar o gráfico de linha do número total de casos segundo o ministério da saúde
por estado.
"""

import pandas as pd

dataset.plot (x = "totalCases", y = "state", kind = "scatter", title = "Casos x Estados", color = "blue")

"""9. Apresentar o gráfico de linha do número total de mortes por estado."""

import pandas as pd

dataset.plot (x = "deaths", y = "state", kind = "scatter", title = "Casos x Estados", color = "blue")

"""11. Apresentar o histograma do número de casos. Formar grupos de 70."""

import pandas as pd

dataset[["totalCases"]].hist (bins = 70, alpha = 0.45, color = "green")

"""12. Apresentar o histograma do número de casos segundo o ministério da saúde. Formar
grupos de 70.
"""

import pandas as pd

dataset[["totalCases"]].hist (bins = 70, alpha = 0.45, color = "green")

"""13. Apresentar o gráfico "boxplot" do número de mortes."""

mpl.style.use ("ggplot")
dataset.boxplot (column = "deaths")

"""14. Apresentar o gráfico "boxplot" do número de mortes segundo o ministério da saúde."""

mpl.style.use ("ggplot")
dataset.boxplot (column = "deaths", by = "state")

"""15. Apresentar o gráfico "boxplot" do número total de casos pelo número de suspeitos."""

mpl.style.use ("ggplot")
dataset.boxplot (column = "totalCases", by = "suspects")