# -*- coding: utf-8 -*-
"""ADSTI_EX17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1osIkisFb1r-FaKf_RuQExgG_9WwtrhA7
"""



"""# **Carregamento**"""

#Carregamento do dataset:
from google.colab import files
src = list (files.upload ().values ())[0]
open ("kc_house_data.csv", "wb").write (src)

"""# **Uso**"""

#Leitura do dataset para um DataFrame:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
print (type (dataset))

"""# **Exemplos**"""

#Imóveis com 5 quartos:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset.loc[dataset["bedrooms"] == 5]

#Quantidade de imóveis com 5 quartos:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset[dataset["bedrooms"] == 5].count ()

#Quantidade de imóveis com 5 quartos:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset.loc[dataset["bedrooms"] == 5] .count ()

#Imóveis com 5 quartos e com mais de 3 banheiros
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset[(dataset["bedrooms"] == 5) & (dataset["bathrooms"] > 3)]

#Ordenar o "DataFrame" pela coluna preço em ordem crescente.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset.sort_values (by = "price")

#ou 
#Ordenar o "DataFrame" pela coluna preço em ordem crescente:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset.sort_values (by = "price", ascending = True)

#Ordenar o "DataFrame" pela coluna preço em ordem crescente:
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset.sort_values (by = "price", ascending = False)

#Agrupar e contar a quantidade de imóveis por número de quartos.
#OBS: em ordem decrescente da quantidade de imóveis.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset["bedrooms"].value_counts()

#ou
#Agrupar e contar a quantidade de imóveis por número de quartos.
#OBS: em ordem decrescente da quantidade de imóveis.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset["bedrooms"].value_counts (ascending = False)

#Agrupar e contar a quantidade de imóveis por número de quartos.
#OBS: em ordem crescente da quantidade de imóveis.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset["bedrooms"].value_counts (ascending = True)

#Agrupar e contar a quantidade de imóveis pelo número de quartos.
#OBS: em ordem crescente do número de quartos.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset["bedrooms"].value_counts().sort_index()

#Agrupar e contar a quantidade de imóveis pelo número de quartos.
#OBS: em ordem crescente do número de quartos.
import pandas as pd
dataset = pd.read_csv ("kc_house_data.csv", sep = ",")
dataset["bedrooms"].value_counts ().sort_index (ascending = True)

"""# **Exercício**

# Carregamento
"""

#Carregamento do dataset:
from google.colab import files
src = list (files.upload ().values ())[0]
open ("brazil_covid19.csv", "wb").write (src)

"""# **Leitura**"""

#Leitura do dataset para um DataFrame:
import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
print (type (dataset))

"""1. Apresentar os registros do Acre."""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset[dataset["state"] == "Acre"]

"""2. Qual o número de registros do Ceará?"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset[dataset["state"] == "Ceará"].count ()

"""3. Quais os registros com mais de 30.000 casos?"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.loc[dataset["cases"] > 30000]

"""4. Qual o número de registros com mais de 15.000 casos?"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.loc[dataset["cases"] > 15000] .count ()

"""5. Quais os registros com mais de 10.000 casos e com mais de 500 mortes?"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.loc[(dataset["cases"] > 10000) & (dataset["deaths"] > 500) ] .count ()

"""6. Qual o número de registros com mais de 5.000 casos e com mais de 100 mortes?"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.loc[(dataset["cases"] > 5000) & (dataset["deaths"] > 100) ] .count ()

"""7. Ordenar os registros em ordem crescente de casos."""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.sort_values (by = "cases")

"""8. Ordenar os registros em ordem crescente de mortes."""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.sort_values (by = "deaths")

"""9. Ordenar os registros em ordem decrescente de data."""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset.sort_values (by = "date")

"""10. Agrupar e contar a quantidade de registros por data. Ordenar em ordem decrescente
de data. Em algum dia, a coleta de dados em algum estado ou no distrito federal não
foi realizada?
"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset["date"].value_counts()

"""11. Agrupar e contar a quantidade de registros por estado. Apresentar os estados em
ordem alfabética.
"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset["state"].value_counts ().sort_index (ascending = True)

"""12. Agrupar e contar a quantidade de registros por região. Apresentar as regiões em
ordem alfabética.
"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset["region"].value_counts ().sort_index (ascending = True)

"""13. Agrupar e contar a quantidade de registros por número de casos. Apresentar o
resultado em ordem decrescente de casos.
"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset["cases"].value_counts ().sort_index (ascending = False)

"""14. Agrupar e contar a quantidade de registros por número de mortes. Apresentar o
resultado em ordem crescente de mortes.
"""

import pandas as pd
dataset = pd.read_csv ("brazil_covid19.csv", sep = ",")
dataset["deaths"].value_counts ().sort_index (ascending = True)